# Generated by Django 4.1.3 on 2022-11-23 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("LmsApp", "0004_what_learn_requirements"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "lesson_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LmsApp.course"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.IntegerField(null=True)),
                (
                    "thumbnail",
                    models.ImageField(null=True, upload_to="Media/yt_thumnail"),
                ),
                ("title", models.CharField(max_length=100)),
                ("youtube_id", models.CharField(max_length=200)),
                ("time_duratiom", models.FloatField(null=True)),
                ("preview", models.BooleanField(default=False)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LmsApp.course"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="LmsApp.lesson"
                    ),
                ),
            ],
        ),
    ]
