# Generated by Django 4.1.3 on 2022-11-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LmsApp", "0006_language_course_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="Deadline",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
