# Generated by Django 4.1.3 on 2022-11-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LmsApp", "0007_course_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="certificate",
            field=models.BooleanField(default=False, null=True),
        ),
    ]
